-- Neon Ping Arena v1.07 global leaderboard
-- Run this once in Supabase SQL Editor.

create table if not exists public.neon_ping_scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 16),
  mode text not null check (char_length(mode) between 1 and 24),
  detail text not null default '' check (char_length(detail) <= 32),
  reward integer not null default 0 check (reward between 0 and 1000),
  score integer not null check (score between 0 and 5000),
  client_version text not null default '1.07',
  created_at timestamptz not null default now()
);

alter table public.neon_ping_scores enable row level security;

revoke all on table public.neon_ping_scores from anon, authenticated;
grant select, insert on table public.neon_ping_scores to anon, authenticated;

drop policy if exists "public leaderboard read" on public.neon_ping_scores;
create policy "public leaderboard read"
on public.neon_ping_scores for select
to anon, authenticated
using (true);

drop policy if exists "public leaderboard submit" on public.neon_ping_scores;
create policy "public leaderboard submit"
on public.neon_ping_scores for insert
to anon, authenticated
with check (
  char_length(player_name) between 1 and 16
  and char_length(mode) between 1 and 24
  and char_length(detail) <= 32
  and reward between 0 and 1000
  and score between 0 and 5000
  and client_version = '1.07'
);

create index if not exists neon_ping_scores_rank_idx
on public.neon_ping_scores (score desc, created_at asc);
